baseURL = "/"
title = "GetSmart Help Internal"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = true

# Uncomment to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# Define taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
taxonomyCloud = ["tags", "categories"]
taxonomyCloudTitle = ["Tag Cloud", "Categories"]
taxonomyPageHeader = ["tags", "categories"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
# pygmentsOptions = "linenos=table"
pygmentsStyle = "tango"

# URL settings
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Service configuration
[services.googleAnalytics]
# id = "UA-00000000-0"

# Language configuration
[languages]
[languages.en]
languageName = "English"
weight = 1
[languages.en.params]
title = "GetSmart Token"
description = "GetSmart Help"

# Markup configuration
[markup]
[markup.goldmark]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"
# Uncomment to use chosen highlight style for code blocks without a specified syntax
# guessSyntax = "true"

[params]
copyright = "Digital Financial Aid Corporation"
privacy_policy = "https://getstoken.org/privacy"
version_menu = "Releases"
archived_version = false
version = "0.0"
url_latest_version = "https://help.getstoken.org"
github_repo = "https://github.com/getsmart-token/gs_help_int"
github_project_repo = "https://github.com/getsmart-token/"
github_branch = "main"
algolia_docsearch = false
offlineSearch = true

# Include custom CSS for site styling
customCSS = ["css/custom.css"]

# User interface configuration
[params.ui]
breadcrumb_disable = false
footer_about_enable = false
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_compact = false
sidebar_search_disable = false

[params.ui.navbar_logo_image]
light = "/images/logo-get-smart.svg"
dark = "/images/logo-get-smart.svg"

[params.ui.navbar]
height = "50px"

# Feedback configuration
[params.ui.feedback]
enable = true
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Reading time configuration
[params.ui.readingtime]
enable = false

# Links configuration
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/getsmart-token/"
icon = "fab fa-github"
desc = "Development takes place here!"

# Module configuration
[module]
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

# Uncomment line below for temporary local development of module
# replacements = "github.com/google/docsy -> ../../docsy"
