# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
command = "npm run build:preview"
publish = "public"
command = "hugo --gc --minify"

[build.environment]
GO_VERSION = "1.20.5"
HUGO_VERSION = "0.133.0"

[context.production]
command = "npm run build:production"
HUGO_ENV = "production"
