# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)
#[build]
#  publish = "public"
#  command = "hugo --gc --minify"

#[build.environment]
#  HUGO_VERSION = "0.133.0"

#[context.production.environment]
#  HUGO_ENV = "production"
